### ISSUE TITLE
Datagrid paging

### ISSUE THREAD

**Issue by kevinwinahradsky** [480Oswego2013/CSC-HCI-480-2013-repo#10]
Right now the data grid in the data tab may not be showing all the data. At most it can retrieve 1024 rows of data from h2o, I'm not sure if that is the default or if the default is lower than that.  

The grid widget being used will support paging so it is something we need to have implemented for larger data sets.

**Comment by kevinwinahradsky** [comment]
Adding this to the uibinder milestone. It is probably too much for that milestone but it should be given an initial look for a level of effort estimate.

**Comment by cbchd** [comment]
Nick looking into it
