### ISSUE TITLE
Datagrid column headers chopped off

### ISSUE THREAD

**Issue by kevinwinahradsky** [480Oswego2013/CSC-HCI-480-2013-repo#11]
The column headers can be chopped off on the right hand side.

**Comment by kevinwinahradsky** [comment]
Would it be too ugly to add side scrolling to this? Can the side scrolling be only when needed?

**Comment by patricktoohey** [comment]
Could do fixed width and ellipsis to shorten text which exceeds width, then show full text on hover.

**Comment by patricktoohey** [comment]
Updated global css to address this issue. Please review and close if this is addressed sufficiently.

**Comment by kevinwinahradsky** [comment]
It looks better but I'm not sure if it is a final solution. Is it possible to have the full name show in a tool tip or something?

**Comment by patricktoohey** [comment]
Implemented wrapping on the headers.

**Comment by kevinwinahradsky** [comment]
Looks nice
