### ISSUE TITLE
Merge prep - Review Request

### ISSUE THREAD

**Issue by kevinwinahradsky** [480Oswego2013/CSC-HCI-480-2013-repo#13]
Working on merging our 3 active branches into one so we easily merge back into the master.
uibinder
h2oapi
build

**Comment by kevinwinahradsky** [comment]
This is ready and should be  a clean merge to master.

Looking for a couple others to verify this.

**Comment by kevinwinahradsky** [comment]
This would be the devmerge branch https://github.com/480Oswego2013/CSC-HCI-480-2013-repo/tree/devmerge

**Comment by patricktoohey** [comment]
Confirmed
1. Parsed Data Sets
2. Pop-outs
3. Generate Forest
4. Generate Secondary Forest

Issue
1. After generate forest, "Trees" button is non-functional
2. After generate second forest, "Trees" button is functional

**Comment by patricktoohey** [comment]
should assign this to Ben next?

**Comment by patricktoohey** [comment]
On a second pass...
1. After generate forest, "Trees" button is functional.
2. After display tree, "Generate Forest" button is non-functional???

**Comment by kevinwinahradsky** [comment]
Yeah at this point the generate forest button only works once. This is intentional and has been that way for a while. Though if it makes no sense for it to work that way it can easily be changed.

**Comment by kevinwinahradsky** [comment]
Is ben a contributor? I'm not sure which username is his if he is.

**Comment by mkhayes** [comment]
I have tested this branch out and it seems to work quite nicely. I say we merge this guy to main so we can finally move on...

**Comment by patricktoohey** [comment]
Closed. Merge to master complete.
