### ISSUE TITLE
Trees Menu Location

### ISSUE THREAD

**Issue by kevinwinahradsky** [480Oswego2013/CSC-HCI-480-2013-repo#19]
Would it make more sense for this to be located on the Confusion Matrix tab rather than on the data tab?

**Comment by patricktoohey** [comment]
I agree. I don't think the list box is of much user either. I would propose we add a textbox, where the user can enter a tree number, and a button to trigger viewing of the tree specified in the textbox. These new controls could be introduced next to the "Trees" label on the confusion matrix view.

**Comment by kevinwinahradsky** [comment]
Yeah, I agree the menu is not very useful either. I was thinking the suggest box would be a good fit, http://gwt.googleusercontent.com/samples/Showcase/Showcase.html#!CwSuggestBox
Another possibility might be to adapt a pager style widget to handle this.

If it is added at the bottom of the panel in the trees section, it may not be that obvious that they exists. Would this be a ui issue or just a user training issue?

**Comment by patricktoohey** [comment]
A pager would work so long as it is effective with very large lists. If we have 1000 trees we need a control that can get us quickly from tree 1 to tree 1000. Also, using the bottom panel would be fine so long as we always display the first tree immediately after building the model.

**Comment by adarwin** [comment]
Note that I did not implement any other form of user input. If we still think that is necessary between now and the end of Spring 2013, we'll need to re-open this issue.
