### ISSUE TITLE
Test issue question.

### ISSUE THREAD

**Issue by mkhayes** [480Oswego2013/CSC-HCI-480-2013-repo#2]
What do the labels duplicate, invalid, and wontfix mean (for issues)?

**Comment by patricktoohey** [comment]
Sound like bug categories.

Duplicate: bug already defined

Invalid: submitter is confused

Won’t Fix: valid bug, but not important

From: mkhayes
Sent: ‎March‎ ‎8‎, ‎2013 ‎10‎:‎51‎ ‎PM
To: 480Oswego2013/CSC-HCI-480-2013-repo
Subject: [CSC-HCI-480-2013-repo] Test issue question. (#2)

What do the labels duplicate, invalid, and wontfix mean?
