### ISSUE TITLE
ProgressBuilderTest Fails

### ISSUE THREAD

**Issue by kevinwinahradsky** [480Oswego2013/CSC-HCI-480-2013-repo#20]
Running edu.oswego.csc480_hci521_2013.shared.h2o.urlbuilders.ProgressBuilderTest
Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.052 sec <<< FAILURE!

Results :

Failed tests:   testProgressBuilderJobAndDestination(edu.oswego.csc480_hci521_2013.shared.h2o.urlbuilders.ProgressBuilderTest)
  testProgressBuilderHashArgs1(edu.oswego.csc480_hci521_2013.shared.h2o.urlbuilders.ProgressBuilderTest)

**Comment by patricktoohey** [comment]
I think it would be helpful if you used junit's assertEquals in these tests. This will ensure we see both the expected and actual values in the output. I may just be missing it, but I do not see these output results (which are essential for troubleshooting the errors) in the build output.

**Comment by kevinwinahradsky** [comment]
RFViewBuilderTest now fails as well!

Running edu.oswego.csc480_hci521_2013.shared.h2o.urlbuilders.RFViewBuilderTest
Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.055 sec <<< FAILURE!

Results :

Failed tests:   testRFViewHashConstructor(edu.oswego.csc480_hci521_2013.shared.h2o.urlbuilders.RFViewBuilderTest)

**Comment by cbchd** [comment]
I'm sure it's a problem with the tests, no worries Kevin. They pass on my end so I'm not sure what's up... I'll take a look today

-----Original Message-----

**Comment by kevinwinahradsky** [comment]
closing since this is now working
