### ISSUE TITLE
Make “Parsed Data Sets” button more visible, more button-like

### ISSUE THREAD

**Issue by nonelement** [480Oswego2013/CSC-HCI-480-2013-repo#27]
Two of three users made at least one error(failed interaction) in trying to open the data set, and as high as 6 errors. The title bar design was recognized as an accepted interface pattern, and at least one user commented that the button placement was what they would expect, given other interfaces they’ve encountered (familiarity).

Severity Rating: 2

**Comment by patricktoohey** [comment]
Add CSS to display a dropdown tick mark. Assign to Anthony for review and/or closure.

**Comment by kevinwinahradsky** [comment]
This looks pretty good to me. I'm going to suggest putting the style in the global css and adding this to the other menus as well.

**Comment by patricktoohey** [comment]
I added a new CSS file that I can access from UIBinder. I have also updated
the "Tree" button to use this style.

**Comment by nonelement** [comment]
This looks great. The only thing I can think of to make this more obvious is a color change, perhaps ala how H2O's bar is represented, but I'd like to test it's current incarnation first.
