### ISSUE TITLE
Add iconography for easy interpretation of available tab actions

### ISSUE THREAD

**Issue by agylardi** [480Oswego2013/CSC-HCI-480-2013-repo#30]
All users were confused with the current representation of the pop-out button. One user expected the current representation to exhibit “close” behavior. Others quickly interpreted the action as pop-out, but expressed that they were confused as to how to reverse the action (pop-in). Two users expressed the desire to close tabs, but after searching for a bit, popping in, and out, and right clicking, found no way to accomplish this.

Severity Rating: 4

**Comment by ibarnick** [comment]
Forgot to reference this item in my commit message (and don't feel like editing the repo history to correct this :p).

I tried experimenting with a few different ways of presenting the "pop-in" functionality to the user. In my recent commit (2869f34c78810b3483c5910d9023ebcda47943ed) I've shown one such solution, which adds an additional small bar with a pop-in button. See the following screenshot:
![screenshot](https://f.cloud.github.com/assets/1637596/413682/c89a61d8-abfa-11e2-8195-7384f877569b.png)

I'm not exactly sure what people had in mind but this can obviously be reversed/changed as needed.

**Comment by nonelement** [comment]
This is a good. We can incorporate this into the tab actions task. We'll report how this performs.

**Comment by kgraham1** [comment]
Users were able to pop out the confusion matrix and tree visualization but were confused when attempting to pop the windows back in. The lack of a pop-in button for these windows is what lead to the confusion. Users did not expect that by clicking the "X" on the window's title bar that it would pop the windows back in.

**Comment by ibarnick** [comment]
I applied the small fix required for the issue @kgraham1 pointed out.

I'm leaving the issue open in case anyone would like to review this, although it should be all set and ready to close.

**Comment by kevinwinahradsky** [comment]
Verified that it works, looks good to me.
