### ISSUE TITLE
Include only descriptive text that is useful to users in tab titles

### ISSUE THREAD

**Issue by agylardi** [480Oswego2013/CSC-HCI-480-2013-repo#31]
All users had difficulty identifying non-data tabs(right hand pane) quickly. This problem became worse once more tabs were opened, but plateaued when the limit of visible tabs were reached (at which point one user was confused by the reordering of tabs, if popped out)

Severity Rating: 3

**Comment by cbchd** [comment]
Put in Tab: Titles (keep light)
Put in Panel: Model key & data key
