### ISSUE TITLE
RFScore API and URL builder

### ISSUE THREAD

**Issue by patricktoohey** [480Oswego2013/CSC-HCI-480-2013-repo#33]
Add api for new sample scoring

**Comment by kevinwinahradsky** [comment]
I'll get this done asap.

**Comment by kevinwinahradsky** [comment]
added in the RFScore url builder 1ce3ce8d1e92ca3e18bf01b23e7048a4359ed6a5

This just redirects to RFView Response in our current H2O. I will look into upgrading H2O to see if this is different in newer versions.

**Comment by kevinwinahradsky** [comment]
this looks good so far
