### ISSUE TITLE
Layering tabs / scrolling tabs so that they don’t overflow the screen

### ISSUE THREAD

**Issue by agylardi** [480Oswego2013/CSC-HCI-480-2013-repo#34]
Once 2-3 tabs had been opened by users, navigating more than the most recent two tabs became impossible (depending on native resolution). One user creatively overcame this obstacle by zooming the interface, but this impacted the rest of the interface negatively

Severity Rating: 5

**Comment by kevinwinahradsky** [comment]
Duplicate of #16

**Comment by agylardi** [comment]
Alright. I'll close this one too.
