### ISSUE TITLE
Confusion matrix using incorrect response variable on RFParams branch.

### ISSUE THREAD

**Issue by mkhayes** [480Oswego2013/CSC-HCI-480-2013-repo#4]
To produce this bug use the cars data set. Click "Parsed Data Set" and select the parsed data set. Click "Generate Forest" and choose Classification Variable = "cylinders", number of trees = 10 (I don't think number of trees is relevant). Press generate model. The confusion matrix is displayed with the incorrect response variable (says variable 7 which is year when cylinders is variable 2) , creating an incorrect confusion matrix.

**Comment by kevinwinahradsky** [comment]
Is this a bug in our code or a bug in h2o code?

**Comment by mkhayes** [comment]
I don't know I haven't looked into it.

**Comment by kevinwinahradsky** [comment]
Ok, i will dig into it later.

**Comment by kevinwinahradsky** [comment]
This should be fixed on your branch now. 7d3eff80798315906a82deaad807ff40f5334650

**Comment by mkhayes** [comment]
Appears to be fixed, thanks Kevin!
