### ISSUE TITLE
Error message during RF parameter selection

### ISSUE THREAD

**Issue by nonelement** [480Oswego2013/CSC-HCI-480-2013-repo#40]
The error message should be changed to indicate what the user has done wrong, and provide suggestions as to how to select a valid combination of options. Currently for a classification variable of "displacement (cc)", and a forest size of 6, this error message appears: 

Incorrect input data: Regression is not supported: Response column must be an integer in the interval [2,254]

Perhaps the message should be closer to: "Incorrect parameter selection: classification variable. Please select another variable." though it should not be present in the list if it's not a valid option. Messages for other params should be similar.

**Comment by cbchd** [comment]
`For 0xData. 0xData can choose the error messages & hViewO will display the appropriate ones.
