### ISSUE TITLE
add more detail to page title

### ISSUE THREAD

**Issue by selenechida** [480Oswego2013/CSC-HCI-480-2013-repo#43]
It would be helpful for the page titles to show more detail, such as what page you are on within 0xdata. Ex: Console <Meeting name> etc. This will be helpful when there are many tabs open.
Thanks!

**Comment by eneil** [comment]
I think you may be looking at the wrong Git Hub section.  This is a student designed section for H20, you may be looking for https://github.com/0xdata/h2o.  That is the H20  Git Hub from 0xData.

**Comment by selenechida** [comment]
You are right! Sorry about that.
