### ISSUE TITLE
Out of Bounds Exception on RFParameter  selection & Feedback

### ISSUE THREAD

**Issue by nonelement** [480Oswego2013/CSC-HCI-480-2013-repo#45]
When generating a forest using the build server, a selection of **"cylinders"** as the classification variable, **75** trees, and to ignore **"name"**, causes an out of bounds exception in the console that provides no feedback in the interface. We received this error several times for other combinations of variables as well.

**Comment by mkhayes** [comment]
I think this is either a problem with H2O or with the data set since I can reproduce the same error using the H2O web interface.

**Comment by 480Oswego2013** [comment]
I'm not sure what to test exactly, when I loaded a data sheet I could not re-produce the error

**Comment by mkhayes** [comment]
You can now select ignore "name" and other columns without problems. I found that selecting "power" as classification variable causes the program to freeze, possibly due to the size of the confusion matrix generated.
