### ISSUE TITLE
Close tab feature.

### ISSUE THREAD

**Issue by mkhayes** [480Oswego2013/CSC-HCI-480-2013-repo#5]
It would be nice if we could close tabs. I think a simple "x" button on the right side of the tab will do. This might be a good task for someone who hasn't done any GWT programming yet.

**Comment by ibarnick** [comment]
Some of this functionality has been implemented on the GWT branch. The development is still ongoing though so it hasn't been merged over yet.

**Comment by kevinwinahradsky** [comment]
This should be pretty doable on the uibinder branch now

**Comment by patricktoohey** [comment]
I believe this is closed. Nick, please review; specifically take a look at close method in DoublePanelActivity.java.

**Comment by ibarnick** [comment]
Looks good. The close tab functionality seemed to have gotten lost in a recent merge commit but it's back now.

Marking as closed.
