### ISSUE TITLE
Deployment Document

### ISSUE THREAD

**Issue by 480Oswego2013** [480Oswego2013/CSC-HCI-480-2013-repo#52]
hey guys leave your comments on the document here and I will get to them

**Comment by kevinwinahradsky** [comment]
Do we want to mention editors in the deployment doc or would this be better served as part of the build doc? or do we want to merge build and deployment instructions? 

Maybe we should just say the war needs to be deployed to a servlet container and make the assumption that someone knows how to do this? Maybe just link to a few popular servlet containers and their instructions on how to deploy a war file? 

It should be noted that our custom version of H2O is what needs to be run for this to work. We do need to make this very clear that the default H2O version will not work with our application. The H2O instance also has the limitation of needing to run on the same machine as the servlet is running.

**Comment by agylardi** [comment]
I am still not sure about this deployment document. I assumed the deployment instruction is also for new user who want to try hViewO. So that is why I suggested it to be more new-user friendly (with clearer instruction than current version). But if it is for developer, I think we can go with more abstract instruction.

But I think we can still give explanation on how to build and run it by using Netbeans as example.

**Comment by 480Oswego2013** [comment]
@kevinwinahradsky question how would you import a file into our application?

@agylardi  how should i make it more abstract how would how can i explain more on net beans

**Comment by 480Oswego2013** [comment]
hey guys please look at the deployment again

**Comment by agylardi** [comment]
Current version is abstract already. Not detail. I think it will be hard for new user to follow it. But again, for whom this deployment document ? "next" developer or potential user that interested in using hViewO ? Current version is more for developers I think. 

I also think the line: "a csv file of your choosing ( comma separated value file)" can be explained more as "datasets to be analyzed using the application. In comma separated value (csv) file or other format that supported by H2O"

**Comment by kevinwinahradsky** [comment]
In my opinion this document should be targeting the user who wants to install and run this. I also think it should be safe to assume they know how to use H20 already and have some technical skills. So while they may not be a developer they should not need detailed instructions on how to run and configure all the applications involved. Just what they need to do for our application. The instructions should also be oriented towards the command line and should not include information about netbeans and eclipse.

That's just my opinion though, it would be good to have some more opinions on who everyone else thinks the target of this doc should be.

**Comment by eneil** [comment]
I think Kevin nailed it perfectly, I don't think some person who has no
background knowledge of the material will be downloading this and running
this,  I imagine the user base that would use this would already have some
prior knowledge of the material.

**Comment by agylardi** [comment]
Alright so basically user who knows H2O already (and also about random forest and statistical program), and have some technical skills.

It just, I think it is not really safe to assume user also know what we know. Also, I think not every user favor command line. I am still suggest there is default instruction which oriented to command line, and the one whoe take one of IDE as example. I think with that we could cover both user preferences.

**Comment by 480Oswego2013** [comment]
I do not how to do command line so if you guys could. I thought a ide would
be easier to keep track of the project.

**Comment by patricktoohey** [comment]
I'm gonna put together a video covering the deployment process. I think
this will lower the bar for the actual documentation.

**Comment by patricktoohey** [comment]
A link to the demo video is available in the deployment doc. I'll do another spin if anyone has comments.

**Comment by kevinwinahradsky** [comment]
Nice video.

**Comment by kevinwinahradsky** [comment]
I view the deployment doc as being something like this....

# Build and Deployment Instructions

## Dependencies
- A [git](http://git-scm.com/) client for accessing our source code.
- [Maven 3](http://maven.apache.org/) is our build tool.
- A [servlet container](http://en.wikipedia.org/wiki/Web_container) for running our app in.
- A running instance of [our H2O fork](https://github.com/480Oswego2013/CSC-HCI-480-2013-repo/blob/master/h2o-fork/h2o.jar) with data sets already loaded.

## Building the app.
- Download the code from [our github repository](https://github.com/480Oswego2013/CSC-HCI-480-2013-repo).
  - git clone https://github.com/480Oswego2013/CSC-HCI-480-2013-repo.git
- Build the war file.
  - mvn package

## Deploy the war file.
- The process for doing this can vary quite a bit from one servlet container to another, so detailed instructions for doing this are beyond the scope of this document. We do however recommend using [Tomcat 7](http://tomcat.apache.org/).

## Run the app.
- Make sure a running version or our H2O fork is running such that it is available on localhost:54321 to the server running the servlet container. You can do this directly or make use of a proxy or tunnels or some sort.
  - java -jar h2o-fork/h2o.jar
  - http://0xdata.com/h2o/try-it-out/
- Data will need to be loaded into the H2O instance using their interface.
  - https://github.com/0xdata/h2o/wiki/How-to-Ingest-Data
- Navigate a browser to where ever the app has been setup to be served from.
  - Once there, in the top left corner there is a "Data Sets" menu. You can select a data set to load it into a tab on the bottom left. From there a forest can be generated by clicking on the "Generate Forest" button.

For a more detailed introduction please watch our [introduction video](http://www.youtube.com/watch?v=L9cX2N61XTA&feature=youtu.be).

**Comment by patricktoohey** [comment]
Looks good to me.

**Comment by agylardi** [comment]
Yeah. Looks good. With the video it also minimize the confusion for user. I think we can go with this.

**Comment by kevinwinahradsky** [comment]
Ok, I have pushed that to the wiki. It can always be changed back if more people decide they dont like it.

**Comment by adarwin** [comment]
We're definitely getting somewhere with this document. How would people feel about the "Building the app" section looking like this?

## Building the app.

On the command line, navigate to wherever you want to store the clone of [our repository](https://github.com/480Oswego2013/CSC-HCI-480-2013-repo). Then download and build hViewO by executing the following commands:

```
git clone https://github.com/480Oswego2013/CSC-HCI-480-2013-repo.git
cd CSC-HCI-480-2013-repo
mvm package
```

**Comment by kevinwinahradsky** [comment]
Works for me

**Comment by patricktoohey** [comment]
After 'mvm package', how would you launch in hosted mode?? That should be
included if we are going to detail a command line process.

On Mon, May 13, 2013 at 10:11 AM, kevinwinahradsky <notifications@github.com

**Comment by kevinwinahradsky** [comment]
I don't think anyone should be launching it in hosted mode unless they are actively developing/debugging the application, anyone else should be running the application in a real servlet container. The section after that that basically says to read the documentation for your chosen servlet container is basically the punt for how to do that.

That being said, to easily run it in tomcat you can do "mvn tomcat7:run". Maybe that can be added in the deploy the war section if it makes sense. Generally I would think the average user of this would be just putting the app on a server somewhere and then not messing with it any further. They wouldn't be firing it up every time they want to use it, it would just be setup somewhere as always available.

**Comment by patricktoohey** [comment]
Adding 'mvn tomcat7:run' is basically what I was looking for.

On Mon, May 13, 2013 at 11:35 AM, kevinwinahradsky <notifications@github.com

**Comment by kevinwinahradsky** [comment]
Ok I added that as a quick start instruction under the deploy the war section.

**Comment by kevinwinahradsky** [comment]
Actually moved it down to the next section, makes more sense there I think.

**Comment by patricktoohey** [comment]
That works. I figure first time through, a potential user will want to just
get it up and running. After, it certainly makes sense to formally host it
directly.

On Mon, May 13, 2013 at 11:51 AM, kevinwinahradsky <notifications@github.com

**Comment by adarwin** [comment]
Yes, I figured the information about where to find the .war file should be in the deployment section, rather than the build section. I was thinking something like this:

## Deploy the war file.

**NOTE: The deployment process can vary quite a bit from one servlet container to another. Consequently, detailed instructions for doing this are beyond the scope of this document.**

After building hViewO via `mvn package` you will find the .war file located at
`./target/CSC480_HCI521_2013-1.0-SNAPSHOT.war`
You can deploy this .war file on your application server of choice.

### Tomcat (Recommended)

TODO: Instructions for Tomcat deployment

### GlassFish

As long as your GlassFish server is properly configured and is up and running, the following command should successfully deploy the hViewO .war file to the GlassFish Application Server

`asadmin deploy target/CSC480_HCI521_2013-1.0-SNAPSHOT.war`

Note that if you want to undeploy hViewO, you would need the following command:

`asadmin undeploy CSC480_HCI521_2013-1.0-SNAPSHOT`

If you run into problems, we recommend referring to the [GlassFish deployment documentation](http://docs.oracle.com/cd/E18930_01/html/821-2432/geyvr.html) for further details.

**Comment by adarwin** [comment]
And I'm thinking the 'run' section should look something like this. I'm not yet familiar with Tomcat deployment, so I'm sure the information on Tomcat needs review.

## Run the app.

### Start H2O (If you haven't already)

Start our custom fork of H2O by executing

`java -jar h2o-fork/h2o.jar`

Now navigate to [http://localhost:54321](http://localhost:54321) and follow the instructions at https://github.com/0xdata/h2o/wiki/How-to-Ingest-Data to load a dataset into H2O.

### Start hViewO
- If deployed in GlassFish, simply navigate to [http://localhost:8080/CSC480_HCI521_2013-1.0-SNAPSHOT](http://localhost:8080/CSC480_HCI521_2013-1.0-SNAPSHOT) to load hViewO.
- If deployed in Tomcat, you can quickly run the application from the command line you can execute the following command:
  
  ```
  mvn tomcat7:run
  ```
  
  Then point your browser at http://localhost:8080/
  
  Once there, in the top left corner there is a "Data Sets" menu. You can select a data set to load it into a tab on the bottom left. From there a forest can be generated by clicking on the "Generate Forest" button.

**Comment by agylardi** [comment]
Hmm. I think it's good more detailed instruction added to the wiki. Could cover more type of user -especially the one who prefer just reading the instruction instead of watching the video.

**Comment by adarwin** [comment]
I'm having trouble getting `mvn tomcat7:run` to work. Either I'm doing something wrong, or we should consider removing it from the "Run the app." instructions.

**Comment by kevinwinahradsky** [comment]
what is the problem?

**Comment by adarwin** [comment]
I figured out what went wrong. When I ran `mvn tomcat7:run`, I already had an instance of Tomcat running. I'll note that in the document for future information.

**Comment by agylardi** [comment]
Anyone wanted to add more on deployment document ? I think it's already good.

**Comment by patricktoohey** [comment]
Looks good to me. I vote "Closed"

**Comment by 480Oswego2013** [comment]
I think its good as well ill close it down

**Comment by adarwin** [comment]
I think I'm done with it, so go ahead and close it.
