### ISSUE TITLE
Test Document

### ISSUE THREAD

**Issue by 480Oswego2013** [480Oswego2013/CSC-HCI-480-2013-repo#53]
The build doc should just include a summery of all the test we made and how they work. feel free to make your own summery and submitt them on the wiki

**Comment by kevinwinahradsky** [comment]
Honestly, I think this would be better to just have the generated javadocs for. Make sure each test is well documented in the code and just generate the javadocs for all the tests.

**Comment by 480Oswego2013** [comment]
not a bad idea- though im no pro at making java docs, any tips on where i should look or how to make them?

**Comment by kevinwinahradsky** [comment]
mvn site && firefox target/site/testapidocs/index.html

**Comment by kevinwinahradsky** [comment]
Since a home page is being created for this app, the entire contents of target/site could be uploaded and made public there.

**Comment by 480Oswego2013** [comment]
the web page is not that ellaborate. its simply a couple of links, to github,to the wiki, and one to the webpage

**Comment by kevinwinahradsky** [comment]
right, when you run "mvn site" it basically generates a website for your app. some of it has already been customized, but a few more tweaks and you pretty much have what is needed.

**Comment by kevinwinahradsky** [comment]
just fire up target/site/index.html and you will see what i am talking about

**Comment by 480Oswego2013** [comment]
how do i do that in netbeans? or terminal 
should i install maven on my machine?
do i need maven 3?

**Comment by kevinwinahradsky** [comment]
run it from the terminal.

**Comment by 480Oswego2013** [comment]
i think im getting close i got a website that looks like java7 api

**Comment by kevinwinahradsky** [comment]
try going up a directory to target/site/index.html and you will see the full site with reports and everything.

**Comment by 480Oswego2013** [comment]
i am not sure we need this page any more since the web page has this included in it already. Ill close it at the end of the day if no one has any objections.

**Comment by patricktoohey** [comment]
provided maven site includes javadocs and test coverage report, so I think
I agree that this is redundant.
