### ISSUE TITLE
initial hViewO branding

### ISSUE THREAD

**Issue by kevinwinahradsky** [480Oswego2013/CSC-HCI-480-2013-repo#6]
The main page title should be changed from "Web Application Starter Project" to "hViewO". The build scripts should be changed to build war files with a base name of hViewO.

**Comment by kevinwinahradsky** [comment]
We may want to skip the build script changes but the title bar change should be easy enough.

**Comment by patricktoohey** [comment]
Updated main.html and icon. Please review and close if complete.

**Comment by kevinwinahradsky** [comment]
Looks good
