### ISSUE TITLE
Popout button formatting

### ISSUE THREAD

**Issue by kevinwinahradsky** [480Oswego2013/CSC-HCI-480-2013-repo#7]
The popout button needs to be better formatted in some way. Currently it overflows its container.

**Comment by kevinwinahradsky** [comment]
Possibly just wrapping this in a horizontal panel would work best?

**Comment by kevinwinahradsky** [comment]
It looks better but is probably not done. This might be easier with small images instead of css.

unassigning myself if someone else wants to give it a shot.

**Comment by patricktoohey** [comment]
I don't think this is what you were going for, but take a look; on devmerge

**Comment by kevinwinahradsky** [comment]
No, I reverted it back. That wasn't quite working either.

**Comment by patricktoohey** [comment]
New revision available for review.

**Comment by patricktoohey** [comment]
If this is acceptable, I suggest we also close Issue #30 and add a new issue requiring an equivalent pop-in button.

**Comment by nonelement** [comment]
The arrow icon that is present in the current build works well, I think. We should discuss what is intuitive and feasible on "pop-in" functionality in class (where we can perhaps visually mark up the interface). In the mean time, I'll poll the others on what they think is a good course of action.

**Comment by kevinwinahradsky** [comment]
looks good, closing
